### ISSUE TITLE
setup.py fails with modern pip

### ISSUE THREAD

**Issue by jayvdb** [sakurai-youhei/lib2to3import#1]
```py
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
```

**Comment by sakurai-youhei** [comment]
**How to replicate it**

```
C:\Users\sakurai\git\lib2to3import>python setup.py test
Traceback (most recent call last):
  File "C:\Users\sakurai\git\lib2to3import\setup.py", line 5, in <module>
    from pip.req import parse_requirements
ModuleNotFoundError: No module named 'pip.req'
```

**Environment**

```
C:\Users\sakurai\git\lib2to3import>python -VV
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]

C:\Users\sakurai\git\lib2to3import>python -m pip -V
pip 20.2.3 from C:\Program Files\Python39\lib\site-packages\pip (python 3.9)
```

**Comment by sakurai-youhei** [comment]
@jayvdb This should be fixed in https://pypi.org/project/lib2to3import/2020.11.17.post1/

Thank you for reporting the issue.
